### ISSUE TITLE
Fetching google api with $auth.fetch

### ISSUE THREAD

**Issue by edanweis** [becem-gharbi/nuxt-auth#11]
I'm getting an error fetching a Google API. 

But it works when I paste my token generated by [OAuth 2.0 Playground](https://developers.google.com/oauthplayground/) in a regular useFetch with Authorization header. 

Why is the token obtained by nuxt-auth not working? Scopes are the same.

```JSON
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
``` 
With the following

**pages/index.vue**
```js
const {getAccessToken} = useAuthSession()
const {$auth} = useNuxtApp()
const playlists = ref(null)

const getPlaylists = async () => {
    const res = await $auth.fetch('https://youtube.googleapis.com/youtube/v3/playlists', {
	    params: {
        	mine: true,
        	part: "snippet,contentDetails",
    	}, 
    })
    playlists.value = res
}
```

**config/auth.tsauth.ts**
```js
oauth: {
    google: {
      clientId: process.env.AUTH_OAUTH_GOOGLE_CLIENT_ID ?? '',
      clientSecret: process.env.AUTH_OAUTH_GOOGLE_CLIENT_SECRET ?? '',
      scopes: 'email profile https://www.googleapis.com/auth/youtube',
      authorizeUrl: 'https://accounts.google.com/o/oauth2/auth',
      tokenUrl: 'https://accounts.google.com/o/oauth2/token',
      userUrl: 'https://www.googleapis.com/oauth2/v3/userinfo'
    }
  }
```

Here I [verify the token](https://developers.google.com/identity/gsi/web/guides/verify-google-id-token) via Google (redacted)
```JSON
{
  "sessionId": "clq5nncxxxxxxxxxxxs60nri",
  "userId": "clq51xxxxxxxxxxxxxxxxwbm",
  "userRole": "user",
  "fingerprint": "819adb32xxxxxxxxxxxxxxxxxxc052e42b375",
  "exp": 1702586743,
  "iss": "nuxt-auth"
}
```

**Comment by becem-gharbi** [comment]
By design the access token is issued by the module, not by the oauth provider. On login the module calls the oauth provider for authentication. Then the module creates the tokens and handles the authorization.

**Comment by edanweis** [comment]
Do I then have to implement a new OAuth flow to obtain an access token that can be used with Google APIs? Or some other kind of token exchange? Can you please provide an example? Thanks @becem-gharbi

**Comment by becem-gharbi** [comment]
This would require a redesign of the backend to handle authorization with the oauth provider. This means verification, refresh and revoke handlers should be dependent on the provider APIs. Are you interested in opening a PR for this feature?

**Comment by edanweis** [comment]
> This means verification, refresh and revoke handlers

Feel free to ignore this PR as it is not a re-design, but simply writes the provider's OAuth's access_token cookie and deletes on logout, #12

**Comment by becem-gharbi** [comment]
To help analyze the issue and its requirements:

- The existant implementation with the built-in authorization server should not be modified. The proposed feature can be enabled via a config option, e.g `oauth.external` and should be disabled by default.
- The feature permits the delegation of the authorization server to the oauth2 provider. The latter should:
  - Issue an access and refresh tokens on login.
  - Refresh the access token on expiration. There should be an endpoint for this. Maybe the route is the `tokenUrl`.
  - Revoke the refresh token. There should be an endpoint for this. A new property `revokeUrl` should be added to the provider configuration.
  - Provide a public key to verify the access token by the module. Refer to [jose](https://github.com/panva/jose/blob/main/docs/functions/jwks_remote.createRemoteJWKSet.md) for implementation. There should be an endpoint for this and maybe the response should be cached. A new property `jwksUrl` should be added to the provider configuration.
- As a drawback custom claims are not supported.
- Refactoring should be made in order to abstract the authorization method (internal or external) on the [utility](https://github.com/becem-gharbi/nuxt-auth/tree/main/src/runtime/server/utils/token) level.
- The authorization methods should not co-exist, meaning a single refresh and access token.

I believe that this would take considerable time to implement and validate. That's why I recommend to try other nuxt modules.

**Comment by edanweis** [comment]
That sounds like the right approach. Are you aware of any other alternatives for Nuxt, besides these?

- [sidebase/nuxt-auth](https://github.com/sidebase/nuxt-auth)
- [jeremycoder/nuxt-iam](https://github.com/jeremycoder/nuxt-iam)
- [studioilgranello/nuxt-jwt-auth](https://github.com/studioilgranello/nuxt-jwt-auth)

I would have thought this was a very common use case. Many external OAuth2 providers like Google, have API resources that do not permit service accounts and rely on access tokens for this reason. Am I missing something? is there a simpler solution? Serverless front-ends seem to rely on externally managed OAuth flows. So do they typically exclude features related to ORM, SOC 2, OWASP security standards, etc.?

**Comment by becem-gharbi** [comment]
You can check these modules from the core team
- https://github.com/Atinux/nuxt-auth-utils
- https://github.com/Hebilicious/authjs-nuxt

Indeed this is the common use case for oauth, authorizing requests to the service APIs. However, in order to support email/password login the module should handle authorization by itself.
