### ISSUE TITLE
refresh token

### ISSUE THREAD

**Issue by Meguais** [becem-gharbi/nuxt-auth#9]
I did auth with Prisma. The auth refresh token changes every time I refresh the page in the demo. How can I do that?

**Comment by Meguais** [comment]
and how can i change the loading page Loading page came after installing  becem-gharbi/nuxt-auth

**Comment by Meguais** [comment]
now i just  if i refresh the page on the homepage the token is not refreshed, can i solve this?

**Comment by becem-gharbi** [comment]
- The refresh token is refreshed via a Nuxt plugin under these [conditions](https://github.com/becem-gharbi/nuxt-auth/blob/f2d4a7dd69fe43b0fe3fccf639e434a7d015a878/src/runtime/plugin.ts#L32). 
- Refer to [docs](https://nuxt.com/docs/api/configuration/nuxt-config#spaloadingtemplate) to change the loading page.

**Comment by becem-gharbi** [comment]
I just want to add a note. Please when creating an issue assign a meaningful title to it, try to focus on a single question and describe it clearly with proper grammar. And understand that it's your responsibility to go through documentation and try to first solve the issue on your own. This is just a friendly reminder. We are all here to learn and give back :). 
I will delete this comment when the issue is closed.

**Comment by Meguais** [comment]
i couldn't, token is not refresh on the homepage when i press f5 , works on other pages sorry
https://youtu.be/5lHCxBOiDaY

**Comment by becem-gharbi** [comment]
I have few notes from the video
- In config options, these `redirect` options are requied `home`, `login`,  `logout`, `callback`. They should be a valid route path ex: `/login`
- Use nuxt built-in router for navigation. Apparently you're using browser API for navigation because the page reloads. Use `NuxtLink` or `navigateTo`.

**Comment by Meguais** [comment]
thank you work ! I didn't make the reditect options , now it works very well
